### ISSUE TITLE
Support Burp XML upload to fortify SSC 22.2.1.0008

### ISSUE THREAD

**Issue by kaushik-1071** [fortify/fortify-ssc-parser-burp#11]
Parser/Fortify SSC unable to process Burp XML artifact. 

Throws an error _'Exception: No valid analysis result was found. Please verify the validity of the result file.'_

**Comment by rsenden** [comment]
Hi, thanks for reporting this. Have you followed the [upload instructions](https://github.com/fortify/fortify-ssc-parser-burp/blob/main/USAGE.md#upload-results)?

When uploading an XML file to SSC, SSC will interpret this as an artifact produced by Fortify products and will not invoke any parser plugins. In order to have SSC recognize an XML file as a Burp XML file and pass it to the parser plugin, you'll need to package the XML file in a zip-file together with an accompanying `scan.info` file containing `engineType=BURP_XML`, and then upload this zip-file to SSC.

**Comment by kaushik-1071** [comment]
Thank you very much!! that helped 👍
